version: '3'
services:
  try:
        build: ./
        command: python crawler.py
        command: sh bashScript.sh
  db:
    image: "postgres:11"
    container_name: "publicApisCrawler"
    restart: always 
    ports:
      - "5333:5333"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_HOST: 'localhost'
      POSTGRES_PORT: '5333'